repos:
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      entry: ruff
      language: python
      files: .py$
      args: [
        # Fixes errors with black
        '--fix',
        # Allow missing docstrings
        '--ignore',
        'D103',
        'D100'
        ]
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      files: .py$
      # Use no config file so it can run not in strict, but VSCode will show strict
      args: ['--config-file=']
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: python
      files: .py$