repos:
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      entry: ruff
      language: python
      files: .py$
      args: ['--fix']
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      files: .py$
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: python
      files: .py$