repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: python
      files: .py$
      args: ['--line-length', '79']
  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: python
      files: .py$
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      files: .py$
  - repo: local
    hooks:
    - id: bandit
      name: bandit
      entry: bandit
      language: python
      files: .py$
      