services:
  async_http_test:
    user: app
    build: .
    volumes:
      - .:/async_http_test_container:cached
    command: sleep infinity
  db:
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    ports:
      - 5432:5432

volumes:
  postgres-data:


secrets:
  postgres_user:
    file: postgres_user.txt
  postgres_password:
    file: postgres_password.txt
  postgres_db:
    file: postgres_db.txt
