services:
  async_http_test:
    user: app
    build: .
    volumes:
      - .:/async_http_test_container:cached
    command: sleep infinity
  db:
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    ports:
      - 5432:5432
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    secrets:
      - grafana_user
      - grafana_password

volumes:
  postgres-data:
  prometheus_data:

secrets:
  postgres_user:
    file: postgres_user.txt
  postgres_password:
    file: postgres_password.txt
  postgres_db:
    file: postgres_db.txt
  grafana_user:
    file: grafana_user.txt
  grafana_password:
    file: grafana_password.txt
