[project]
name = "async_http_test"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = ["requests", "rich", "httpx", "aiohttp", "aiofiles"]

[project.optional-dependencies]
dev = [
    "flake8",
    "black",
    "pylint",
    "mypy",
    "pydocstyle",
    "pytest",
    "pre-commit",
]
